### ISSUE TITLE
Verificar correo

### ISSUE THREAD

**Issue by end222** [unizar-30226-2019-07/API#10]
Para realizar la verificación del correo se realizará una petición POST a la dirección "/verify" con el parámetro random, el cual será igual a la cadena de caracteres que aparece en la dirección Web que recibe el usuario que se ha registrado en el correo.
De esta manera, para verificar un usuario:
`api:8080/verify?random=fads7412dfas`

Se ha acordado que únicamente se verificarán correos a través de la página Web, ya que resulta más cómodo verificar una cuenta enviando un link de la página Web al correo del usuario recién registrado.
Por lo tanto las peticiones a la dirección anterior serán realizadas únicamente por el grupo de Interfaz Web.

**Comment by torvic98** [comment]
Para comprobar que lo he entendido:

1. El usuario es registrado mediante el método [POST `/users`](https://unizar-30226-2019-07.github.io/API/#tag/users/paths/~1users/post) enviando un JSON con los datos requeridos.

1. La consulta a [GET `/users/{user_id}`](https://unizar-30226-2019-07.github.io/API/#tag/users/paths/~1users~1{user_id}/get) en este punto devolvería para dicho nuevo usuario un JSON con `status: 'pending'`.

1. La aplicación de Back-end genera un código aleatorio ÚNICO (úsese [`UUID`](https://docs.oracle.com/javase/7/docs/api/java/util/UUID.html)`.randomUUID().toString()`) que almacena en la base de datos y luego envía un correo electrónico con dicho UUID a la dirección proporcionada en el registro con formato: `www.selit.com/verify?token=fads7412dfas` dónde `www.selit.com` es la dirección de la interfaz web.

1. Cuando la aplicación web recibe dicha petición, envía a la API una petición al Controlador `api.selit.com:8080/verify?random=fads7412dfas` con `api.selit.com` la dirección de la API.

1. El Back-end trata esa petición:
    1. En caso afirmativo, cambia el `status` del usuario a `active` y ELIMINA el `token` de la base de datos. Devolverá un código de respuesta `200`.
    1. En caso negativo, se devolverá un error `404`.

**Comment by victorpowah** [comment]
2. Status: “bloqueada”
3. Random no token
5. Status: “activa”

**Comment by torvic98** [comment]
La especificación de la API es clara: `active`  `inactive`  `pending`

**Comment by victorpowah** [comment]
Pero cuando se realizo el diseño de la base se establecio ese ENUM
