### ISSUE TITLE
Añadir un método para validar el token de sesión de un usuario

### ISSUE THREAD

**Issue by diegoroyo** [unizar-30226-2019-07/API#11]
## Problema
Cuando un usuario inicia sesión por primera vez este recibe un token de sesión, válido durante cierto tiempo. En el caso de la aplicación móvil, este se almacena en el dispositivo.

Al iniciar la aplicación móvil se intenta leer, si existe, este token guardado:
- Si **no** existe ningún token almacenado, se redirige al usuario a la pantalla de login
- Si existe un token almacenado, no hace falta redirigir al usuario al inicio de sesión

El problema viene cuando el token expira, ya que no se puede detectar hasta hacer una petición a un método que lo necesite y entonces es cuando se pediría al usuario iniciar sesión.

## Solución

Propongo añadir un método para comprobar si un token es válido o no, de forma que si el token ha expirado se pueda detectar a tiempo y redirigir al usuario.

**Comment by torvic98** [comment]
Propongo que hagas una petición genérica a cualquier método,
preferiblemente al método de recuperar el perfil de usuario. Usando ese
método para saber si el token sigue siendo válido. Además os servirá para
mantener actualizada la información del usuario en la app (ante cambios de
nombre o imagen desde la web).

Así no es necesario especificar otro método.

**Comment by aeri** [comment]
De acuerdo, entonces solicitaré siempre al inicio de la sesión la información del usuario.
