### ISSUE TITLE
No puede haber 402 prohibido al buscar un usuario ya que se devuelve su información pública

### ISSUE THREAD

**Issue by victorpowah** [unizar-30226-2019-07/API#14]

**Comment by torvic98** [comment]
Gracias por el apunte. Mañana revisaré lo que comentas y lo modificaré para que sea correcto.

**Comment by torvic98** [comment]
- [ ] Eliminar 402 de `/users` (GET) y `/users/{user_id}` (GET).
- [ ] Eliminar 402 de `/products` (POST).
