### ISSUE TITLE
Añadir documentación para '/login'

### ISSUE THREAD

**Issue by diegoroyo** [unizar-30226-2019-07/API#15]
Si no me equivoco de nombre, el método `/login` para iniciar sesión ya se encuentra implementado. Solamente falta añadir su documentación correspondiente.

**Comment by torvic98** [comment]
¿Os importaría decirme exactamente cómo estáis usando ese método? Ponedme la especificación informal aquí y yo me encargo de documentarlo mañana.

**Comment by victorpowah** [comment]
/login
request body:
email(equired) 
password(required)

Response ->
Header:
Authorization: (token)
