### ISSUE TITLE
Añadir "Listar los productos de un usuario"

### ISSUE THREAD

**Issue by torvic98** [unizar-30226-2019-07/API#18]
Puede ser útil (por ejemplo, de cara a mostrar el perfil de un usuario) poder listar todos los productos que un usuario tiene publicados.

Para ello habría dos opciones:

1. `/users/{user_id}/products`
1. `/products?owner={user_id}`

¿Cuál veis más útil y coherente con el resto de la API?

**Comment by victorpowah** [comment]
La segunda es la mas coherente bajo mi criterio

**Comment by aeri** [comment]
Veo más agradable la primera por el hecho de no andar con variables GET.

**Comment by end222** [comment]
Yo la verdad veo bien las 2 opciones. Son diferentes maneras de plantearlo pero no prefiero una sobre otra. Si que es verdad que, como ha dicho Naval, puede resultar más sencilla de implementar la primera al no tener que tratar con parámetros en peticiones GET.

**Comment by victorpowah** [comment]
Bueno, tambien seria como un filtro para products por lo que creo que cuadra mas ahi, pero como veais.

**Comment by torvic98** [comment]
> La segunda es la mas coherente bajo mi criterio

Considero que crear un nuevo parámetro de filtro es más coherente con el desarrollo actual de la API.


> Veo más agradable la primera por el hecho de no andar con variables GET.

Puesto que ya existen parámetros GET para el resto de filtros, deberíais estar (o estaréis) habituados con dicha forma de filtrar por variables GET.

Propongo optar por la opción 2:

> 2.  `/products?owner={user_id}`
