### ISSUE TITLE
Añadir filtro "En venta/Vendido" para obtener productos

### ISSUE THREAD

**Issue by torvic98** [unizar-30226-2019-07/API#19]
¿Interesaría a los equipos poder obtener productos "en venta" o "vendidos" por separado? Se me ocurre lo siguiente:

1. Homogeneizar las propiedades de los productos (tipo `sale` y `auction`):
    1. Mantener el *enum* de `sale` con su significado actual:
        - `on sale`: En venta, se pueden realizar ofertas por chat.
        - `reserved`: El vendedor ha aceptado una oferta y está pendiente de quedar con el comprador.
        - `sold`: Vendido, la transacción se ha completado.
    1. Cambiar el *enum* de `auction` al significado:
        - `on sale`: En venta, se pueden realizar pujas (equivale a `bidding` actual).
        - `reserved`: Fin de la subasta, se ha adjudicado al mejor postor, pendiente de quedar entre comprador y vendedor. (equivale a `awarded` actual).
        - `sold`: Vendido, la transacción se ha completado.
1. Crear un parámetro *query* en `/products` para filtrar según es `status`: `on sale`, `reserved`, `sold`.

**Comment by victorpowah** [comment]
1) En el diseño inicial de la base solo se habian contemplado los estados vendido o en venta ya que no se vio necesario que se supiera que esta reservado. Vendido podria cubrir perfectamente esa opcion.

2) Añadir el filtro es facil asique como veais

**Comment by end222** [comment]
Coincido en que sería una buena idea añadir un filtro sobre productos para facilitar su obtención.
Por otra parte, en cuanto a lo de lo del estado del producto en cuanto a su disponibilidad, coincido con victorpowah en que no sería necesario la utilización del estado "reservado", ya que no se haría ninguna diferenciación frente al estado "vendido".

**Comment by torvic98** [comment]
Muy bien, dejo pendientes las siguientes adaptaciones:

-  Cambiar estados de productos a "en venta" y "vendido". (Confirma, @victorpowah, que sean esos los nombres)
-  Añadir un filtro *query* `status` a `/products`.

**Comment by victorpowah** [comment]
Si, son esos los nombres @torvic98
