### ISSUE TITLE
Revisar especificación de 'Crear nuevo usuario'

### ISSUE THREAD

**Issue by diegoroyo** [unizar-30226-2019-07/API#2]
Crear nuevo usuario: https://unizar-30226-2019-07.github.io/API/#tag/users/paths/~1users/post

En la especificación los campos `status` y `rating` son obligatorios para registrar un nuevo usuario.

No se deberían pasar y, por ejemplo, al crear el nuevo usuario se puede asignar un valor por defecto a estos campos.

**Comment by torvic98** [comment]
Solucionado en c8447af8046c58f30fbce29734290e4ed98ed925. Estableciendo ambos campos como `readOnly` ya no se puede pasar esa información en los métodos `PUT` y `POST`.

El campo `rating` se calculará como derivado de cada una de las valoraciones.
El campo `status` se deberá cambiar haciendo uso de un Controlador (véase #4).
