### ISSUE TITLE
Documentación errónea para la información de productos

### ISSUE THREAD

**Issue by diegoroyo** [unizar-30226-2019-07/API#20]
## Operaciones referenciadas

* [Obtener lista de productos](https://unizar-30226-2019-07.github.io/API/#tag/products/paths/~1products/get)
* [Obtener información de un producto](https://unizar-30226-2019-07.github.io/API/#tag/products/paths/~1products~1{product_id}/get)

## Problema

La información de la documentación está desactualizada con lo que devuelve realmente la API tras realizar una petición, en concreto **la información obtenida de un producto en concreto** (ya sea en una lista o uno solo):

|                      | **Respuesta petición API** | **Documentación**                  |
|----------------------|----------------------------|------------------------------------|
| ID de producto       | `id_producto`              | `id`                               |
| ID de usuario        | `id_owner`                 | _(no aparece)_                       |
| Distancia            | Valor `double`             | Valor `int`                        |
| Fecha de publicación | `publicate_date` (`2019-04-05`)           | `published` (`2017-07-21T17:32:28.000Z`) |
| Precio               | Valor `double`             | Valor `int`                        |
| Likes                | `nfav`                     | `likes`                            |
| Visitas              | `nvis`                     | `views`                            |

He intentado ponerlo detallado para facilitar todo lo posible la discusión, espero no haberme dejado nada.

## Ejemplo

Al hacer una petición para obtener la lista de productos sin aplicar ningún filtro se obtiene el siguiente resultado:

```
[{"publicate_date":"2019-04-05","description":"Color gris/plata. Año 1986. 47000 km. El coche está en perfecto estado.","title":"Porsche 911 Turbo s","location":{"lat":-34.397,"lng":150.644},"price":2500.0,"currency":"EUR","nfav":0,"nvis":0,"id_owner":79,"category":"Automocion","status":"vendido","owner":{"idUsuario":79,"gender":null,"birth_date":null,"posX":0.0,"posY":0.0,"rating":1.0,"status":null,"password":null,"email":"callefalsa1234@nasa.net","last_name":"Necesito Ayuda","first_name":"Andrew Necesito Ayuda","tipo":null},"distance":15121.107763433301,"id_producto":77}]
```

**Comment by torvic98** [comment]
La especificación era clara, el problema lo ha introducido el grupo de *back-end*.

**Comment by diegoroyo** [comment]
Vale, sin problema, he escrito la issue para marcar las diferencias.

@victorpowah que el equipo de back-end le eche un vistazo a esto cuando pueda
