### ISSUE TITLE
Obtener un producto: lat y lng no tienen sentido

### ISSUE THREAD

**Issue by victorpowah** [unizar-30226-2019-07/API#21]
En esta operación se busca el producto con el id dado, por lo que ningún atributo mas tendrá sentido.
@torvic98

**Comment by torvic98** [comment]
Echa un vistazo a la issue #16, creo que es donde solicitaste esos parámetros.

Si me equivoco dímelo.

**Comment by victorpowah** [comment]
Bueno que se olvido una s me referia a que los de la funcion obtener productos tenian que ser required. @torvic98
