### ISSUE TITLE
Problema al devolver productos.

### ISSUE THREAD

**Issue by aeri** [unizar-30226-2019-07/API#22]
La API no devuelve productos en la pantalla inicial si hay algún producto con divisa USD, hay que realizar una búsqueda detallada para que empiecen a aparecer.

**Comment by torvic98** [comment]
No entiendo lo que dices, @aeri, en la web haciendo una consulta a `/products` se obtienen todos los productos independientemente de la divisa usada.

Un ejemplo:

![image](https://user-images.githubusercontent.com/13553098/56082282-5aac2280-5e17-11e9-9be7-0cfe1ba4848f.png)

**Comment by vpec** [comment]
El bug fue algo momentáneo. Sin realizar ningún cambio luego comenzó a funcionar perfectamente.
