### ISSUE TITLE
Lista de las posibles categorías para un producto

### ISSUE THREAD

**Issue by diegoroyo** [unizar-30226-2019-07/API#23]
Cada producto tiene asignada una categoría, que se puede seleccionar de una lista. No sé si el backend ha decidido ya una lista de categorías, pero en caso de que no haya ninguna lista propongo usar estas categorías:

- Automoción
- Informática
- Moda
- Deporte y ocio
- Videojuegos
- Libros y música
- Hogar y jardín
- Foto y audio

He intentado no hacerla demasiado larga porque no creo que necesitemos más, pero si queréis añadir/modificar/eliminar alguna categoría, adelante.

**Comment by torvic98** [comment]
Decisión a tomar: @end222, @aeri, @victorpowah 
¿El nombre de las categorías será el mismo que lo que devuelva en el JSON, o se usarán nombres resumidos? Ej: `Foto y audio` --> `foto_audio`

**Comment by end222** [comment]
@torvic98 Yo diria que mejor que sea el mismo nombre, que seguramente nos resulte más sencillo.

**Comment by victorpowah** [comment]
Yo opino como @end222

**Comment by torvic98** [comment]
La nomenclatura de categorías propuesta por @diegoroyo se considera aceptada. 

**ATENCIÓN:** Se acaba de modificar la base de datos para soportar estas categorías. (CC: @victorpowah)
