### ISSUE TITLE
Al realizar una puja, en la petición se envía la cantidad de dinero pero no la moneda, algo que podría dar problemas si son de distintos tipos.

### ISSUE THREAD

**Issue by AndrewKM210** [unizar-30226-2019-07/API#24]

**Comment by torvic98** [comment]
Las pujas en una subasta se hacen en la divisa en la que se dio el precio de salida del producto. Siguiendo ese razonamiento, no sería necesario volver a indicar el tipo de divisa.

**¿Por qué se hace así?**
Si cada puja fuese en una divisa distinta, el grupo de _backend_ debería tener una base actualizada de la cotización de las diferentes divisas (i. e. www.xe.com) para poder comprobar, por ejemplo, que una nueva puja candidata de 100 USD es superior a una puja anterior de 90 EUR.
