### ISSUE TITLE
Añadir un error 409 (conflicto) si un usuario quiere borrar a otro que no es el suyo.

### ISSUE THREAD

**Issue by victorpowah** [unizar-30226-2019-07/API#7]

**Comment by torvic98** [comment]
¿Existe algún tipo de permisos de usuario (i.e. `admin`) que permita borrar usuarios ajenos o, por contra, un administrador sólo podrá poner `status: 'inactive'` pero nunca eliminarlo?

**Comment by victorpowah** [comment]
Los admin pueden borrar cualquier usuario y los usuarios solo asi mismos, si intentan borrar a otro saltara el error 409.

**Comment by torvic98** [comment]
De acuerdo, pero el error debería ser `402 - Forbidden`, que indica que el usuario identificado no tiene permiso para realizar la operación. ¿Supondría eso un problema?

**Comment by victorpowah** [comment]
No, ningún problema
