### ISSUE TITLE
Crear/actualizar producto: pasar el ID de usuario en lugar de un objeto User

### ISSUE THREAD

**Issue by diegoroyo** [unizar-30226-2019-07/API#8]
## Operaciones referenciadas
- [Crear nuevo producto](https://unizar-30226-2019-07.github.io/API/#tag/products/paths/~1products/post)
- [Actualizar producto](https://unizar-30226-2019-07.github.io/API/#tag/products/paths/~1products~1{product_id}/put)

## Problema
El atributo `owner` se puede simplificar, de forma que solamente se reciba el ID de dicho usuario en lugar de un objeto con campos _required_ (email, nombre, etc.), que creo que no hace falta.

En otras operaciones, como [obtener un producto](https://unizar-30226-2019-07.github.io/API/#tag/products/paths/~1products~1{product_id}/get) tiene más sentido que devuelvan todos los datos del usuario, ya que al menos en la interfaz móvil se van a emplear para mostrar la información de ese usuario.

**Comment by torvic98** [comment]
Tienes razón, en que sólo es útil en las operaciones de consulta. Por la forma en la que funciona [OAS3.0](https://www.openapis.org/) por defecto utiliza el mismo JSON para todos los casos, intentaré cambiarlo para que se adapte a lo que propones.
