### ISSUE TITLE
Filtro de 'users' por email

### ISSUE THREAD

**Issue by end222** [unizar-30226-2019-07/API#9]
Se ha añadido en la implementación el filtro por email a la hora de obtener una lista de usuarios con la finalidad de permitir al usuario logeado conseguir su identificador. La sintaxis sigue el estándar, de manera que sería así:
`direccion:8080/users?email=pabloorduna98@gmail.com`

**Comment by torvic98** [comment]
Si te he entendido bien, estás haciendo referencia al parámetro `email` que ya existía en la [operación GET 
 `/users` de la API](https://unizar-30226-2019-07.github.io/API/#tag/users/paths/~1users/get). ¿Es necesario que modifique algo o puedo cerrar el Issue?

**Comment by victorpowah** [comment]
Esta correcto.
